package com.sistema.gestao.socios.mapper;

import com.sistema.gestao.socios.dto.RelatorioFinanceiroRequestDTO;
import com.sistema.gestao.socios.dto.RelatorioFinanceiroResponseDTO;
import com.sistema.gestao.socios.model.RelatorioFinanceiro;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

import java.util.List;

@Mapper(componentModel = "spring")
public interface RelatorioFinanceiroMapper {

    RelatorioFinanceiroMapper INSTANCE = Mappers.getMapper(RelatorioFinanceiroMapper.class);

    // Maps Request DTO to Entity (used for triggering generation)
    // Ignore fields that are generated by the service
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "dadosRelatorio", ignore = true)
    RelatorioFinanceiro toRelatorioFinanceiro(RelatorioFinanceiroRequestDTO dto);

    // Maps Entity to Response DTO
    RelatorioFinanceiroResponseDTO toRelatorioFinanceiroResponseDTO(RelatorioFinanceiro relatorio);

    // Maps List of Entities to List of Response DTOs
    List<RelatorioFinanceiroResponseDTO> toRelatorioFinanceiroResponseDTOList(List<RelatorioFinanceiro> relatorios);

    // Update is likely not applicable
}
